### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by tanrax**

### CODE REVIEW

**Comment by shymega** [comment]
You haven't given me any context for this PR? What exactly are you 'fixing'? I'm rewriting `singlerss` to use a combination of AWS Lambda, CloudWatch, and S3, so this repo is sorta out of date.

**Comment by tanrax** [comment]
There is no justification. I did a fork and since I took the trouble to update the dependencies myself, I thought it would be interesting to share them. 
I have tested that it works fine with the new versions.
I take this opportunity to thank you for sharing the code, it has helped me a lot and I have learned some good practices from your code.

**Comment by shymega** [comment]
Hey, sorry for the late reply. I was really humbled to see my code helped you make your own project. This project is moving in the 'Serverless' direction at the moment. I'm gonna merge this PR, thanks! The idea with the new direction is that a user can hit the Lambda, which gets the RSS feeds as it does now, and puts it into an S3 bucket. Then the user can call the Lambda on a different API Gateway endpoint, and use it as a frontend to the S3 bucket's `singlerss` file. It's going to be renamed to `single-rss`.

Thank you again!

**Comment by tanrax** [comment]
A very interesting objective/project.
Thanks to you!

**Pull request merged**
